---
- hosts: ec2
  remote_user: ubuntu
  sudo: true
  vars:
        max_connections: 110
        temp_file_limit: 10
        listen_addresses: "'*'"
        wal_level: "hot_standby"
        max_wal_senders: 5
        wal_keep_segments: 32
        archive_mode: "on"

        entries: |
                local   all             postgres                                trust
                local   all             all                                     trust
                host    all             all             127.0.0.1/32            trust
                host    all             all             ::1/128                 trust
                host    all             replication     54.173.52.161/32        md5
                host    all             replication     54.152.253.76/32        md5
  handlers:
        - name: reload postgres config
          sudo_user: postgres
          shell: psql -c "select pg_reload_conf()"
  tasks:
        - name: update apt cache
          apt: update_cache=yes
        - include: tasks/omnipitr.yml
        - include: tasks/postgresql.yml
