---
- hosts: postgres_master
  remote_user: ubuntu
  sudo: true
  vars:
          archive_command: "'scp %p /home/postgres/walarchive/%f'"
  handlers:
        - name: reload postgres config
          sudo_user: postgres
          shell: psql -c "select pg_reload_conf()"
  tasks:
        - name: copy customized postgresql.conf file
          template:
                src: templates/postgresql.conf.j2
                dest: /etc/postgresql/9.3/main/postgresql.conf
          notify:
                - reload postgres config

